### ISSUE TITLE
Failed to start process, "ts-node" exec not found

### ISSUE THREAD

**Issue by GeorgeBarlow** [flaviuse/mern-authentication#133]
As per title, ``` failed to start process, "ts-node" exec not found``` when simply running the dev environment with the provided docker image.

Any solution to this?

**Comment by flaviuse** [comment]
Thanks for the catch, There was an issue with the dev script, I modified the tooling use it should be fixed now. Let me know if you still have issues

**Comment by flaviuse** [comment]
Tested in code space, it now works, closing the issue for now.
