### ISSUE TITLE
savedUser is undefined

### ISSUE THREAD

**Issue by jacobkossman** [flaviuse/mern-authentication#17]
Had an error when trying to register or do anything with the API. In the [auth.js](https://github.com/flaviuse/mern-authentication/blob/cb139d68b73b82fa523d668f4b8921c495b249c1/server/routes/auth.js#L266) route. Once you switch this to `user.email` instead it works.

Didn't wanna bother sending a whole pull request for such a tiny thing 👍  Also a quick thing is to switch the sending email as a variable or an environmental variable as I didn't realize i needed to change it.

Thanks for your work, hopefully this will be a great bootstrap for a ecommerce stack I'm building.

**Comment by flaviuse** [comment]
@jacobkossman Thanks for the catch ! I fixed it and added your suggestion with an optional env variable. I'm happy that my work can help you with projects :)
