### ISSUE TITLE
Email not being sent

### ISSUE THREAD

**Issue by ncesar** [flaviuse/mern-authentication#25]
I've tried to run without docker so I had to setup two .envs

This is the backend:
```
NODE_ENV=development
MONGO_URI=mongodb-atlas-url
PORT=8081
HOST=localhost:3000
SENDGRID_API_KEY=sendgrip-api
SENDING_EMAIL=email
SESSION_KEY=my key
```

frontend:
```
NODE_ENV=development
REACT_APP_API_URL=http://localhost:8081
REACT_APP_WEBSITE_NAME=hello
CHOKIDAR_USEPOLLING=true
```

but I'm receiving this annoying message: `*Impossible to send an email to ceesar90@gmail.com, try again. Our service may be down`.

But the API key is totally correct and I have all the enviroments that Docker has. What I may be doing wrong? Is there any additional setup to run without Docker?

Also, I have one question: Is there any simple way to completely disable e-mail verification/sending/forgot? I don't really need them atm.

**Comment by flaviuse** [comment]
> 
> but I'm receiving this annoying message: `*Impossible to send an email to ceesar90@gmail.com, try again. Our service may be down`.
> 
> But the API key is totally correct and I have all the enviroments that Docker has. What I may be doing wrong? Is there any additional setup to run without Docker?

Hello, can you tell me exactly when you receive this error ? Just when starting the server ? When trying to signup ?
If it is when just launching, have you installed dotenv for the backend, .env files are supported by default via create react app but not for the backend.
If it is when trying to signup, the error occur when failling to send the email with SendGrid:
![image](https://user-images.githubusercontent.com/40322270/96991667-14b23d80-1529-11eb-82e8-3957ef7cbb22.png)
Try to console.log the error given by sendgrid to see what is the problem. 
Can you attach your error from the network tab of browser as well, it could help for debugging.

> 
> Also, I have one question: Is there any simple way to completely disable e-mail verification/sending/forgot? I don't really need them atm.
Not currently

**Comment by ncesar** [comment]
Hi @flaviuse thanks for the quick answer.

This is what I'm getting:
![image](https://user-images.githubusercontent.com/29064514/97039739-446e3f00-1543-11eb-9084-f35f512c8d31.png)

**Comment by flaviuse** [comment]
> Hi @flaviuse thanks for the quick answer.
> 
> This is what I'm getting:
> ![image](https://user-images.githubusercontent.com/29064514/97039739-446e3f00-1543-11eb-9084-f35f512c8d31.png)
> 

could you parse the error message please

**Comment by flaviuse** [comment]
Most likely a SendGrid issue (maybe check here: https://github.com/sendgrid/sendgrid-python/issues/885), I can't do anything without the error.
Closing for now.
