### ISSUE TITLE
Log in not working

### ISSUE THREAD

**Issue by Whizkevina** [flaviuse/mern-authentication#5]
Running the app locally, after creating an account when redirect to login, the login feature is not working, it's constantly complaining of "Invalid username or password", which the route in the API can be found in ```routes/auth.js``` on line 35...
Does it mean the user round is not been saved or what...

**Comment by flaviuse** [comment]
> Running the app locally, after creating an account when redirect to login, the login feature is not working, it's constantly complaining of "Invalid username or password", which the route in the API can be found in `routes/auth.js` on line 35...
> Does it mean the user round is not been saved or what...

Is the user validated on the DB ? Check your mongo DB to see if the user has been created

**Comment by flaviuse** [comment]
@Whizkevina Do you still encounter the issue ?

**Comment by Whizkevina** [comment]
@flaviuse, Yes I still encounter the issue on it...

**Comment by flaviuse** [comment]
@Whizkevina I could not reproduce your issue, local version is working well on my side, I'll update the code soon to have last versions of libraries.

The error "Invalid username or password" appear when the user provided for login is invalid meaning that it does not exist in your DB, check if the username exist in your DB with mongoDB compass.

![image](https://user-images.githubusercontent.com/40322270/79686071-c3558880-823d-11ea-9b95-6938d66c0707.png)


You can try a fresh install with, make sure : 
- Mongo DB instance is running on your computer, use MongoDB compass to check your DB.
- Environment variables are properly set up on client and serve (read README.md they are described).
- You have a correct Sendgrid API key to send the confirmation email (can have https problem here change the url of the confirmation link to http)

When registering you should have a new user and a token created in your DB : 
![image](https://user-images.githubusercontent.com/40322270/79685978-fe0af100-823c-11ea-83e1-419d4327265c.png)
![image](https://user-images.githubusercontent.com/40322270/79685985-0b27e000-823d-11ea-84f0-cc8e52de4717.png)

**Comment by Whizkevina** [comment]
@flaviuse, thank you so much for your timely support.
I appreciate it.

**Comment by flaviuse** [comment]
@Whizkevina No problem ;) If you need help don't hesitate
