### ISSUE TITLE
 error      TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by vall370** [flaviuse/mern-authentication#6]
Hello!
Thanks for a wonderful boilerplate.
Ive followed the steps and it worked so far, but whenever i hit refresh I get the following error TypeError: Object(...) is not a function.
Any ideas what it might be? Ive added console.log in the backend and get HTTP error 304 but serialized user is still in session.

How may i fix this?

Thanks
error stack:
 error      TypeError: Object(...) is not a function
    at user (user.js:18)
    at combination (redux.js:445)
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
    at Object.dispatch (redux.js:205)
    at e (<anonymous>:1:40553)
    at redux-logger.js:1
    at index.js:11
    at middleware.js:25
    at dispatch (redux.js:611)
    at user.js:7

**Comment by flaviuse** [comment]
> Hello!
> Thanks for a wonderful boilerplate.
> Ive followed the steps and it worked so far, but whenever i hit refresh I get the following error TypeError: Object(...) is not a function.
> Any ideas what it might be? Ive added console.log in the backend and get HTTP error 304 but serialized user is still in session.
> 
> How may i fix this?
> 
> Thanks
> error stack:
> error TypeError: Object(...) is not a function
> at user (user.js:18)
> at combination (redux.js:445)
> at p (:1:36402)
> at v (:1:36684)
> at :1:40069
> at Object.dispatch (redux.js:205)
> at e (:1:40553)
> at redux-logger.js:1
> at index.js:11
> at middleware.js:25
> at dispatch (redux.js:611)
> at user.js:7

Hello ! I think the problem is that when you reload, the app calls the backend to get the user.
![image](https://user-images.githubusercontent.com/40322270/87230849-b1a1fe00-c3b2-11ea-8fed-6a3126d285b4.png)
Do you have session cookies in your browser in the frontend when it crash ? Is your user still in your database and session ?
The frontend crash because it seems that there is no error catching on the request to the backend to load the user (my bad here). 

Verify your DB if the user is here, I think there are error gaps in the app. I'll check into it next week.

**Comment by vall370** [comment]
Hi!

I've sent you a private repo invite. 
You were right about the nodejs not retrieving user from databas

This is the logs when I sign in and reload the page:

When logging in....
OPTIONS /api/auth/login 204 1.393 ms - 0
Session {
cookie:
{ path: '/',
\_expires: null,
originalMaxAge: null,
httpOnly: true },
passport: { user: '5f0b917bb912030a4059f64d' } }
POST /api/auth/login 200 245.460 ms - 262

When reloading....
Session {
cookie:
{ path: '/',
\_expires: null,
originalMaxAge: null,
httpOnly: true },
passport: { user: '5f0b917bb912030a4059f64d' } }
GET /api/user 304 96.728 ms - -

MongoDB

{
"\_id": "c7flltf8VAfoCYxm6qvowLm7CORc_2b7",
"expires": {
"\$date": "2020-07-26T23:37:14.205Z"
},
"session": "{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"passport\":{\"user\":\"5f0b917bb912030a4059f64d\"}}"
}

Browser Cookie value
s%3Ac7flltf8VAfoCYxm6qvowLm7CORc_2b7.AYJGK7NdWvIdWEPs2e5zFJFcJQC3kdnvH2XT3Z6JAAA
