### ISSUE TITLE
Logging in always says "*Invalid email or password."

### ISSUE THREAD

**Issue by wolfy01** [flaviuse/mern-authentication#96]
This is also with a fresh clone of the project with all correct environmental variables.

**Comment by flaviuse** [comment]
You should check the database and see if the user has been created properly after registration, if you got a validation email and you validated the account that should be the case. I could not reproduce with a fresh install

**Comment by wolfy01** [comment]
Hmm.. What node version do you happen to be using? The user appears to be created just fine and the user is verified.

**Comment by flaviuse** [comment]
Are you using the docker compose setup ? The node version is defined in the the docker image, it is version 14.16

**Comment by wolfy01** [comment]
> Are you using the docker compose setup ? The node version is defined in the the docker image, it is version 14.16

Yes, I am. I forgot docker specifies the node version 😂. Im currenting using docker desktop on windows, does that matter?

**Comment by flaviuse** [comment]
I use docker desktop as well on windows, it should not change anything the code is running in the same environment container. Are you trying to connect with the username or email of the account you created ? Connection with email will not work with the frontend even if the API support it. 
You can add logging in the code to check what is happening: (winston.info)
![auth route](https://user-images.githubusercontent.com/40322270/146682338-7d99e821-2ed8-4a9d-bdf7-ef43c349f680.png)
That will log in the server: 
![log](https://user-images.githubusercontent.com/40322270/146682394-bd85ef29-9703-4c22-926b-ea44f5514f89.png)

**Comment by wolfy01** [comment]
> I use docker desktop as well on windows, it should not change anything the code is running in the same environment container. Are you trying to connect with the username or email of the account you created ? Connection with email will not work with the frontend even if the API support it. You can add logging in the code to check what is happening: (winston.info) ![auth route](https://user-images.githubusercontent.com/40322270/146682338-7d99e821-2ed8-4a9d-bdf7-ef43c349f680.png) That will log in the server: ![log](https://user-images.githubusercontent.com/40322270/146682394-bd85ef29-9703-4c22-926b-ea44f5514f89.png)

Thank you. I shall try this in a few minutes. I also tried logging in with username and email just to check.
